# Python basics week 03: class of 3/10
working with packages --> numpy, pythonic code
arrays, ...

Let's say you've got problems with packages --> https://www.dataquest.io/blog/install-pip-windows/

In [ ]:
! pip install numpy

## Importing Numpy

In [2]:
import numpy
import numpy as np
from numpy import arange

## Creating arrays
Arrays --> all elements have to be the same type, similar to c#

In [ ]:
import numpy as np
list = [1,5,8,10,3]
print(list)

array = np.array(list)
print(array)

#list --> seen as a whole and can now be added completely twice
#array will store each element and multiply it.

print(list * 2)
print(array * 2)

list.append(2)
print(list)
#array.append(2) --> just doesn't work, because of fixed size

#1D arrays
print(np.arange(10)) #every number equivalent to indexes from 0 - 9
print(np.zeros(10)) #10 0's --> x amount of 0's
print(np.ones(10))
print(np.full(10,5))

print(np.random.randint(-5,6, 10)) #generates random numbers, low point, high point (not inc), amount
print(np.random.random(10)) #random floats in array of size x

[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]
[1, 5, 8, 10, 3, 2]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[-5  0  0  0 -5 -3 -4 -3  0 -5]
[0.37452751 0.7403231  0.09985537 0.69115539 0.42420549 0.24835703
 0.16446974 0.02870403 0.25901008 0.16001038]


## Reshaping and converting arrays

In [44]:
import numpy as np
#for safety --> calling array again and giving it values
array = np.random.randint(-5,6,10)
print(array)
print(array.shape) #length
print(array.ndim) #number of dimensions of your array

print("array has number of datatype:", array.dtype)

array_float = array.astype('f') 
#astype converts from a type into the other
#i - integer / b - boolean / f - float / M - datetime / S - string / however words also work --> str, int, bool, float
print(array_float)
array_string = array.astype(str)
print(array_string)

#2D arrays
array_2D = np.reshape(array, (2,5))
print(array_2D)
print(array_2D.ndim)
print(array_2D.shape)

array_2D = np.reshape(array, (5,2))
print(array_2D)

#reshaping has to result in a perfect match --> cannot reshape into something that the original cannot be split by
#array_2D = np.reshape(array, (3,3))
#print(array_2D)

array_2D = np.reshape(array, (10,1)) #also possible
print(array_2D)

array_2D = np.reshape(array, (-1,5))
print(array_2D)


[-3 -2  0 -5  0  3 -4 -2  0  4]
(10,)
1
array has number of datatype: int32
[-3. -2.  0. -5.  0.  3. -4. -2.  0.  4.]
['-3' '-2' '0' '-5' '0' '3' '-4' '-2' '0' '4']
[[-3 -2  0 -5  0]
 [ 3 -4 -2  0  4]]
2
(2, 5)
[[-3 -2]
 [ 0 -5]
 [ 0  3]
 [-4 -2]
 [ 0  4]]
[[-3]
 [-2]
 [ 0]
 [-5]
 [ 0]
 [ 3]
 [-4]
 [-2]
 [ 0]
 [ 4]]
[[-3 -2  0 -5  0]
 [ 3 -4 -2  0  4]]


## slicing arrays
[start : end : step]
- start = starting index
- end = ending index (not included)
- step = stepsize

In [ ]:
import numpy as np
array = np.array([6, 8, 2, 9, 3, 1, 4, 7, 0, 5])
print(array)

print(array[1:5:1]) #[8 2 9 3]
print(array[1:5:])#default step is same as 1
print(array[1:5:2]) #[8 9]

print(array[0:5:1]) #[6 8 2 9 3]
print(array[:5:1]) #[6 8 2 9 3]

print(array[0::1]) #[6 8 2 9 3 1 4 7 0 5]
print(array[0:10:1])

#reverse
print(array[::-1])
print(array[::-2])

print(array[0:10:-1]) #shows nothing
print(array[10::-1]) #leave the end blank to do the full reverse, else you just add your index (not included)


[6 8 2 9 3 1 4 7 0 5]
[8 2 9 3]
[8 2 9 3]
[8 9]
[6 8 2 9 3]
[6 8 2 9 3]
[6 8 2 9 3 1 4 7 0 5]
[6 8 2 9 3 1 4 7 0 5]
[5 0 7 4 1 3 9 2 8 6]
[5 7 1 9 8]
[]
[5 0 7 4 1 3 9 2 8 6]


## Some extra work with arrays

In [83]:
a = np.arange(0, 10)
b = np.arange(9, -1, -1)
print(a,b)
print(a + b)
print(a - b)
print(a * b)
print(np.where(a % 2 == 0, a + 1, a)) #--> condition, x, y --> x if true, y if false

print(np.where(b > 5))
print(np.where(b > 5, b, 0))
print()

b = np.reshape(b, (2, 5))
print(b)
print()

print(b.sum(axis=0)) #sum of columns
print(b.sum(axis=1)) #sum of rows
print(b.cumsum(axis=1)) #cumulative sum of numbers, calculating then printing 1 at a time.

print()
print(a.sum())
print(a.min())
print(a.max())

print(np.sqrt(a))
print(np.sqrt(a.max()))

[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]
[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[1 1 3 3 5 5 7 7 9 9]
(array([0, 1, 2, 3]),)
[9 8 7 6 0 0 0 0 0 0]

[[9 8 7 6 5]
 [4 3 2 1 0]]

[13 11  9  7  5]
[35 10]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]

45
0
9
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
3.0


### Exercise: It's magic time!!!
Read in a 1D array and a number of rows! Convert the array to 2D, calculate the sum of each column and if all sums are equal --> provide a message saying: it's a magic table<br><br>

<b>input</b><br>
2 7 0 8 4 1 1 0 10<br>
3<br>
<b>output</b><br>
True
<pre>
2 7 0<br>
8 4 1<br>
1 0 10<br>
<i> 11 11 11</i> --> MAGIC TABLE
</pre>

In [ ]:
import numpy as np
s = input() # 2 7 0 8 4 1 1 0 10
array1D = np.array(s.split(" "))
array1D = array1D.astype(int)
rows = int(input())
col = int(len(array1D) / rows)

array = np.reshape(array1D, (rows, col))
print(array)

sums = np.sum(array, axis = 0) #0 = cols
print(sums)

total = np.sum(sums)
if total // rows == sums[0]:
    print("MAGIC TABLE")
else:
    print("NO MAGIC TABLE")


[[ 2  7  0]
 [ 8  4  1]
 [ 1  0 10]]
[11 11 11]
MAGIC TABLE
